### ISSUE TITLE
二进制上传报错

### ISSUE THREAD

**Issue by LoveLifeLoveSelf** [tripleCC/binary-server#7]
终端输入：curl http://localhost:8881/frameworks -F "name=BundleImageCache" -F "version=2.0.6" -F "file=BundleImageCache.framework.zip"

服务器报错如下:
TypeError: Cannot read property 'name' of undefined
      at create (/Users/yangxinlin/cocoapods-bin-example/binary-server/server/controllers/frameworks.js:64:48)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async logger (/Users/yangxinlin/cocoapods-bin-example/binary-server/node_modules/koa-logger/index.js:67:7)

**Comment by tripleCC** [comment]
> 终端输入：curl http://localhost:8881/frameworks -F "name=BundleImageCache" -F "version=2.0.6" -F "file=BundleImageCache.framework.zip"
> 
> 服务器报错如下:
> TypeError: Cannot read property 'name' of undefined
> at create (/Users/yangxinlin/cocoapods-bin-example/binary-server/server/controllers/frameworks.js:64:48)
> at processTicksAndRejections (internal/process/task_queues.js:97:5)
> at async logger (/Users/yangxinlin/cocoapods-bin-example/binary-server/node_modules/koa-logger/index.js:67:7)

request body 没拿到上传的 file
