### ISSUE TITLE
服务器连接数据库错误

### ISSUE THREAD

**Issue by LoveLifeLoveSelf** [tripleCC/binary-server#8]
app.js 里面修改了主机地址
const Koa = require('koa')
const router = require('./server/routes')
const logger = require('koa-logger')
const mongoose = require('mongoose')
const koaBody = require('koa-body')

const app = new Koa

mongoose.connect('mongodb://10.10.10.13/binary_database')

app.use(koaBody({ multipart: true }))
app.use(logger())
app.use(router.routes())
app.listen(8080)

执行 弄的app.js时报错如下：

(node:61058) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [10.10.10.13:27017] on first connect [MongoNetworkError: connection 0 to 10.10.10.13:27017 timed out
    at Socket.<anonymous> (/Users/zhaopin/binary-server/node_modules/mongodb-core/lib/connection/connection.js:258:7)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
    at Socket._onTimeout (net.js:480:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)]
    at Pool.<anonymous> (/Users/zhaopin/binary-server/node_modules/mongodb-core/lib/topologies/server.js:505:11)
    at Pool.emit (events.js:315:20)
    at Connection.<anonymous> (/Users/zhaopin/binary-server/node_modules/mongodb-core/lib/connection/pool.js:329:12)
    at Object.onceWrapper (events.js:422:26)
    at Connection.emit (events.js:315:20)
    at Socket.<anonymous> (/Users/zhaopin/binary-server/node_modules/mongodb-core/lib/connection/connection.js:256:10)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
    at Socket._onTimeout (net.js:480:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:61058) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:61058) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by LoveLifeLoveSelf** [comment]
尝试过重启数据库，重启服务都不好使

**Comment by LoveLifeLoveSelf** [comment]
已经解决，数据湖初始路径没有设置。参考链接：https://www.runoob.com/mongodb/mongodb-osx-install.html
